name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was modified."
          done
