- name: Get changed files using defaults
  id: changed-files
  uses: tj-actions/changed-files@v46
- name: List all added files
  run: |
     for file in ${{ steps.changed-files.outputs. modified_files }}; do
        echo "$file was modified."
     done
